### ISSUE TITLE
[BUG] 메시지 내역 조회 기능 구현

### ISSUE THREAD

**Issue by Pascal-Case** [ClassBridge/ClassBridge-BE#36]
## Description
메시지 내역 조회 기능 구현

## Todo List
- [x] 메시지 모델 및 저장소
- [x] 메시지 서비스 로직
- [x] 메시지 컨트롤러 로직

## ETC
- 메시지 모델 및 저장소
  - ChatMessage 모델 생성
  - ChatMessageRepository 생성
- 메시지 서비스
  - ChatMessageService 생성 및 메시지 내역 조회 로직 추가
- 메시지 컨트롤러
  - ChatMessageController 생성
  - 메시지 내역 조회 엔드포인트 추가
