### ISSUE TITLE
[FEAT] 구글 회원가입 기능 추가

### ISSUE THREAD

**Issue by minsoo0506** [ClassBridge/ClassBridge-BE#6]
## Description
구글 회원가입 기능 추가

## Todo List
- [x] SecurityConfig 클래스 구현
- [x] CorsMvcConfig 클래스 구현
- [x] User 엔티티 생성, UserRepository 생성
- [x] User 컨트롤러 구현(signup 메소드 : 구글 회원가입 사용자 뿐만 아니라, 이메일로 회원가입 하는 사용자의 경우에도 사용 가능)
- [x] UserService 클래스 구현(getUserFromGoogle 메소드, getUserDto메소드) 
- [x] 회원가입에 사용되는 Dto 클래스 구현 - AuthDto, UserDto, AdditionalInfoDto, OAuth2Response, GoogleResponse
- [x] CustomOAuth2UserService 클래스 구현 : 사용자 정보 획득 과정 중 실행할 로직 구현
- [x] CustomSuccessHandler 클래스 구현 : 사용자 정보 획득 성공 이후 실행할 로직 구현
- [x] Util 클래스 구현 - JWTUtil, CookieUtil
