### ISSUE TITLE
[FEAT] search 기능

### ISSUE THREAD

**Issue by ykchoi1203** [ClassBridge/ClassBridge-BE#61]
## Description
search 기능 추가

## Todo List
- [x] opensearch config, gradle 추가
- [x] search 에 사용할 document 추가
- [x] search 기능 추가
